@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Accept: application/json
Content-type: application/json

{

"url": "https://docker.com",
"pointOfContact": {
    "name": "Silvio",
    "email": "silvio@jbrain.com",
    "phone": "800 Write-Code"
}
}


### 

GET {{SoftwareCenter.Api_HostAddress}}/vendors/e506c810-taco-salad


### 
GET {{SoftwareCenter.Api_HostAddress}}/vendors/
